[package]
name = "tw-merge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
css-color = "0.2.8"
tailwind-ast = "=0.4.1"
