[package]
name = "tw_variant_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.20.8"

tw_fuse = { path = "../fuse" }
tw_utils = { path = "../utils" }
