[package]
name = "tw_fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_ast = { path = "../ast" }
nom = "7.1.3"

[dev-dependencies]
divan = "0.1.14"
fastrand = "2"

[[bench]]
name = "merge"
harness = false

[features]
debug = []
