name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Run clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Check README.md
        run: |
          set -e
          cargo install cargo-rdme
          cargo rdme --check
      - name: Warning for README.md check failure
        if: ${{ failure() }}
        run: |
          echo "README.md check failed. Please run 'cargo rdme' to update your README.md based on doc comments."
          exit 1